### ISSUE TITLE
Naming suggestion for binaries

### ISSUE THREAD

**Issue by lebouquetin** [buxx/trsync#30]
I suggest to name every binary with a name matchin the following pattern : `trsync-xxx` or `trs-xxx`

This way, autocomplete in CLI will be easier for a user who does not know exactly what are the involved binaries.

Examples:

- rename `configure` to `trsync-config` (`configure` is a common command name for configuring a project before to build it)
- rename `trsync_manager_systray` to `trsync-systray-manager`

**Comment by buxx** [comment]
Good idea 👍
