### ISSUE TITLE
Windows10: Space name on Windows is not the same like I have in tracim directly

### ISSUE THREAD

**Issue by PhilippeAccorsi** [buxx/trsync#49]
## At present

Some of space not show the good name of space. I think it is because some space have emoji inside name.

## Expected

The good name is show or something inform user about "some caracters can't be showing correctly"

**Comment by buxx** [comment]
Yes names are live modified to avoid crash because of emojis :(

This case of errors will be solved by https://github.com/buxx/trsync/issues/45

**Comment by buxx** [comment]
Solved by last update
